SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS Bloodsugar;
DROP TABLE IF EXISTS Pulse;
DROP TABLE IF EXISTS DataProvider;
DROP TABLE IF EXISTS ServiceProvider;
DROP TABLE IF EXISTS DeletedData;

SET FOREIGN_KEY_CHECKS = 1;
